### ISSUE TITLE
Reporting not working in the mixin-maven-plugin

### ISSUE THREAD

**Issue by jgpelaez** [odavid/maven-plugins#1]
From my company, we want to use the mixin-maven-plugin, as we trust more the way of parsing the pom files in this one than in the tiles.
Would it be possible to collaborate with the project, we want to add the possibility to generate a pom, and add some testing / continuos integration.

**Comment by odavid** [comment]
Hi,
First of all thanks for being interested in the mixin-maven-plugin. It warms my heart (:.
I'll be happy to get help. How can I help you?

**Comment by odavid** [comment]
Hi,
I've released version 0.1-alpha-34 which supports merging reporting section.
Regarding collaboration, I would prefer pull requests at the moment.
Hope this helps,
Ohad
