### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by danhaywood** [odavid/maven-plugins#10]
Hi Ohad,

just wanted to say thanks for putting this plugin together.  I've been using it to create a small catalogue of mixins (danhaywood/java-mavenmixin-* on https://github.com/danhaywood?tab=repositories) which I'll be using to simplify the next version of the archetype we ship to get started with Apache Isis (http://isis.apache.org/).

Thanks again
Dan

**Comment by odavid** [comment]
Hi Dan,

Sorry for the late response.
Just wanted to say it makes me glad that it helped you.

Cheers
Ohad

**Comment by danhaywood** [comment]
Yeah, thanks again.

I ended up with these mixins: http://www.danhaywood.com/2016/11/24/maven-mixins/

Cheers
Dan
