### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by tombensve** [odavid/maven-plugins#2]
I decided to try the mixing-maven-plugin as an alternative to tiles-maven-plugin (which is causing me some strange problems). But unfortunately the mixing-maven-plugin fails on things that tiles handles fine.

I have a tile/mixin for building groovy. In the top level of the pom it has the following:

```
<project ...>
   ...
    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.3.11</version>
            <scope>compile</scope>
            <classifier>indy</classifier>
        </dependency>
    </dependencies>
```

Then it uses maven-antrun-plugin to do compilation. The compilation however fails with the following message:

```
[ERROR] java.lang.NoClassDefFoundError: groovy/lang/GroovyObject
```

The first thing I tried was to also put the groovy dependency within the maven-antrun-plugin. This however gives the same result. I also tried only having the dependency in the maven-antrun-plugin but that did not help either.

The funny thing is that it is actually finding the groovyc ant task and starts it. It is the ant task that fails to find the basic groovy classes, which are all available in the groovy-all dependency.

However adding the groovy dependency to the "client" pom does work. This however lessens the mixin. I want to put everything groovy related in the groovy pom and just include it. This works with tiles (which however gets confused when you include many tiles). 

I'm hoping this is an error and not a feature :-). 

And thanks for providing one more solution to a problem that should have been solved by maven itself a long time ago IMHO.

**Comment by tombensve** [comment]
I found a workaround to this by adding a profile in my root pom that is activated by the existence of src/main/groovy which then provide the groovy dependency and calls the mixin. I was afraid of having to add both the groovy dependency and the mixin to all poms having groovy code. But now this is solved transparently, and I can still break out things into separate poms making the root pom not so gigantic. 

Having multiple profiles all using mixing-maven-plugin works perfectly even when multiple profiles are activated at the same time.  

I'm however leaving the issue open in case the described behavior is not intended.

**Comment by odavid** [comment]
Thanks for trying out the mixin-maven-plugin.

The mixin-maven-plugin does not provide dependency and dependencyManagement support on purpose. The reason for that are transitive dependencies. 
Think of a case that you deploy your artifact to a repository and someone else which does not use the mixin plugin is depending on your artifact. Since you did not declare a dependency to groovy-all, the third-party consumer will fail to compile, even though your artifact do compile with it.

The plugin tries to supplement the exiting maven native dependency and dependency management capabilities and not to override them.

I think that a better approach would be to define a dependency to groovy in the mixin pom, and then use the mixin pom within the consumer as both a dependency pom (depchain) and as a mixin. 
This way is a bit more "verbose", but keeps the consumer pom a native pom for other third-party consumers.

I'll try to create an example of what I described here.

Hope it makes sense,
Ohad

**Comment by tombensve** [comment]
This makes perfekt sense, I do understand what you are saying :-). The one thing I keep forgetting about maven: the transitive dependencies! I need to get that into my head :-).

I also did not think of the possibility to depend on the mixin as an artifact also thus getting the groovy-all dependency as a transitive dependency. That would work fine. 

I have actually replaced tiles-maven-plugin with mixin-maven-plugin now. The mixin plugin works with the latest maven version (3.3.1) tiles does not. The mixin plugin also merges nicely when I call it several times by having it in profiles where more than one profile might be active. I was afraid that would cause problems, but no, it works perfectly. 

I do have a small feature request, maybe I should add it as such on the github project: Allow for printout of which mixins were included in the maven build run. This would make it much easier to trouble-shoot. Also when I specify an incorrect mixin artifact, one that does not exist, nothing happens, no warning, no error. At least a warning would be nice, but personally I think such an error should break the build.

Best Regards,
Tommy Svensson

**Comment by odavid** [comment]
Hi,
If you run mvn with debug level (-X option) you'll see all the list of mixins that are being merged.
Regarding the incorrect mixin artifact, the code is designed to fail if there is no artifact resolved. If you try to put "foo:bar:1.0" as mixin coordinates, you will fail during the mixin merge phase. Can it be that incorrect mixin artifact is an artifact that you previously built and it exist in your local repository?

Hope it helps,
Ohad

**Comment by odavid** [comment]
I am closing this issue

**Comment by tombensve** [comment]
The -X option helped. I haven't had time to test the foo:bar:1.0 yet, but I buy your theory :-).
