### ISSUE TITLE
settings.xml

### ISSUE THREAD

**Issue by chaimt** [odavid/maven-plugins#6]
what do i need to do to add the package type in my settings.xml

**Comment by odavid** [comment]
Hi Chaim,
I am not sure I understand the question. Can you elaborate?

**Comment by chaimt** [comment]
how to i compile my mixin, when compiling i get unknown packaging

**Comment by odavid** [comment]
Hi Chaim,
Enabling the mixin packaging type is done by declaring the mixin-maven-plugin in the pom with extensions=true. This adds the mixin packaging as a new packaging type and let maven install and deploy mixin.xml file as *.mixin to the repository.
Hope it helps,
Ohad
